name: Build, test, validate

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      generate-catalog:
        required: true
        type: boolean
    secrets:
      token:
        required: true

jobs:
  build_and_test:
    name: '${{ matrix.os }}: build and test'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.runs-on) }}

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: true
    - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        name: catalog
      if: inputs.generate-catalog != true
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '20.x'
    - run: npm install
    - run: npm run generate-catalog
      env:
        GITHUB_TOKEN: ${{ github.token }}
      if: inputs.generate-catalog == true
    - run: npm run test
    - uses: ./
      name: validation test by running get-cmake
    - name: CMake version check
      run: |
        which cmake
        cmake --version
        CMAKE_LATEST=`cat .latest_cmake_version`
        CMAKE_VER="$(cmake --version)"
        if ! [[ "$CMAKE_VER" =~ .*"${CMAKE_LATEST}".* ]]; then
          echo "ASSERTION FAILED! Instead of '${CMAKE_LATEST}', found: "
          echo "$CMAKE_VER"
          exit -1
        fi
      shell: bash
    - name: ninja version check
      run: |
        which ninja
        ninja --version
        NINJA_LATEST=`cat .latest_ninja_version`
        NINJA_VER="$(ninja --version)"
        if ! [[ "$NINJA_VER" =~ .*"${NINJA_LATEST}".* ]]; then
          echo "ASSERTION FAILED! Instead of '${NINJA_LATEST}', found: "
          echo "$NINJA_VER"
          exit -1
        fi
      shell: bash
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: catalog
        path: |
          .latest_ninja_version
          .latest_cmake_version
          src/releases-catalog.ts
      if: inputs.generate-catalog == true